language: node_js
sudo: false

node_js:
  - "10"

cache:
  directories:
  - node_modules

jobs:
  include:
    - stage: deploy
      if: (branch = master) AND (NOT (type IN (pull_request)))
      script:
        - npm install
        - npm run build:h5
      deploy:
          provider: s3
          access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
          secret_access_key: $AWS_SECRET_KEY
          bucket: www.gregreda.com
          endpoint: www.gregreda.com.s3-website-us-east-1.amazonaws.com
          region: us-east-1
          skip_cleanup: true
          local-dir: .temp
          acl: public_read
          detect_encoding: true
          on:
            branch: master
